// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Personalized recommendation AI agent.
 *
 * - getPersonalizedRecommendations - A function that provides personalized recommendations based on user preferences.
 * - PersonalizedRecommendationsInput - The input type for the getPersonalizedRecommendations function.
 * - PersonalizedRecommendationsOutput - The return type for the getPersonalizedRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizedRecommendationsInputSchema = z.object({
  travelDates: z
    .string()
    .describe('The travel dates, as a string. Example: 2024-12-25 to 2025-01-05'),
  budget: z.number().describe('The budget for the trip in USD.'),
  interests: z
    .string()
    .describe(
      'A comma separated list of interests.  Example: history, beaches, nightlife'
    ),
});
export type PersonalizedRecommendationsInput = z.infer<
  typeof PersonalizedRecommendationsInputSchema
>;

const PersonalizedRecommendationsOutputSchema = z.object({
  flightRecommendations: z
    .string()
    .describe('Personalized flight recommendations based on the inputs.'),
  activityRecommendations: z
    .string()
    .describe('Personalized activity recommendations based on the inputs.'),
});
export type PersonalizedRecommendationsOutput = z.infer<
  typeof PersonalizedRecommendationsOutputSchema
>;

export async function getPersonalizedRecommendations(
  input: PersonalizedRecommendationsInput
): Promise<PersonalizedRecommendationsOutput> {
  return personalizedRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'personalizedRecommendationsPrompt',
  input: {schema: PersonalizedRecommendationsInputSchema},
  output: {schema: PersonalizedRecommendationsOutputSchema},
  prompt: `You are a travel expert specializing in Dubai.

  Based on the travel dates, budget, and interests provided, suggest personalized flight and activity recommendations.
  Make sure to tailor the recommendations to Dubai.

  Travel Dates: {{{travelDates}}}
  Budget: {{{budget}}}
  Interests: {{{interests}}}

  Format your response as follows:

  Flight Recommendations: <flight_recommendations>
  Activity Recommendations: <activity_recommendations>`,
});

const personalizedRecommendationsFlow = ai.defineFlow(
  {
    name: 'personalizedRecommendationsFlow',
    inputSchema: PersonalizedRecommendationsInputSchema,
    outputSchema: PersonalizedRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
